### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by RemWisteria** [zxhd863943427/siyuan-plugin-math-enhance#1]
An error about paths occurred while loading the plugin.
![image](https://github.com/zxhd863943427/siyuan-plugin-math-enhance/assets/65723878/00924781-3918-4e8c-b6de-7da9a59ae3c1)

**Comment by zxhd863943427** [comment]
This is a problem with the calling library, which checks itself from a js or ts file at startup, but after being packaged it actually runs as eval, so the check fails.
But this will not affect the function, because this check is used to load the sound and font, I turned off the sound of the keyboard key, and the required font is the katex used by Siyuan.

**Comment by zxhd863943427** [comment]
In addition, if the plugin is malfunctioning, it is most likely because you are not using the latest dev version, which uses the latest interface and requires dev3 or higher to run.
